HELLO-SHELL/HELLO-SHELL

- subject_analysis.md
> FEAT: 과제분석 초안

- src/built_in/env.c
> FEAT: env 함수 만듦. 함수 안에 struct 넣어놓음

- Makefile
makefile에 j 옵션을 줌
1초라도 아껴서 윤택한 삶을 누립시다.
> HS-41 FEAT: add -j option

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
1초라도 아끼기위해 디버깅 버튼 눌렀을 때 pretask로 `make debug` 해줌
> HS-43 FEAT: 디버깅 버튼 눌렀을 때 컴파일도 해줌

- .gitignore
.gitignore 에 추가
macOS, Linux, C, VSCode, Vim 관련 gitignore 생성
이 사이트 애용하세요 -> [gitignore](https://www.toptal.com/developers/gitignore)
> HS-44-git-ignore-추가

- include/minishell.h
- test/built_in_unit_test.c
- test/unit_tester.sh
built_in unit tester
test 폴더에서 테스트할 함수만 남기고 나머지는 주석처리한 뒤에  `bash unit_tester.sh`를 실행하면 함수 실행과 닉체크까지 해줌
> HS-48 unit test

- Makefile
- include/minishell.h
- src/utils/get_env_by_key.c
- test/utils_fun_unit_test.c
- test/utils_fun_unit_test.sh
1. 키값들로 환경변수를 찾는 함수 만듦
2. 테스트 완료
> HS-58 환경변수 key값으로 찾기

- Makefile
rl_replace_line() 함수를 사용하기 위해 makefile 수정
컴파일 과정에 readline 라이브러리를 추가하도록 함
클러스터 환경에서 컴파일 가능
개인 환경에서 컴파일이 안될 수 있음
> HS-62-makefile-링킹-추가

- include/minishell.h
- src/executor/pipe.c
pipe 관련 함수 추가
t_pipes 구조체 추가
헤더 약간 변경
> HS-67-pipe-util-함수들-추가하기

- Makefile
- include/minishell.h
- src/built_in/ft_export.c
- src/executor/executor.c
- src/executor/heredoc.c
- src/executor/pipe.c
- src/executor/redirect.c
- src/executor/safe_func.c
- src/init.c
> HS-66-execute-pipeline-구현하기

- include/minishell.h
- src/utils/env_utils/env_key_valid_checker.c
- src/utils/env_utils/get_env_by_key.c
- src/utils/replace_dollar/replace_dollar.c
-  [x] make the function that return a value, which matched the input key.
동작 확인
> HS-72 FEAT: $가 여러개 있을 경우에도 대응

- Makefile
- include/minishell.h
- src/executor/executor.c
- src/executor/heredoc.c
- src/executor/wait.c
- src/init.c
- src/utils/replace_dollar/replace_dollar.c
> HS-76 달러치환 오류 처리

- Makefile
- include/minishell.h
- src/built_in/ft_cd.c
- src/built_in/ft_export.c
- src/built_in/ft_unset.c
- src/executor/executor.c
- src/executor/heredoc.c
- src/executor/wait.c
- src/init.c
- src/main.c
- src/utils/env_utils/env_utils.c
- src/utils/free_utils/free_utils.c
- src/utils/replace_dollar/replace_dollar.c
* executor 에 입력한 커맨드가 builtin 함수인지 아닌지 확인하는 코드
* 확인했으면 실행하는 코드
echo 는 추가해야함
> Hs 84 isbuiltin

- Makefile
작업 환경 따라 readline 경로 flags 변경
스크린샷 참조
> HS-86-makefile-change-to-react-for-various-readline-flags-in-various-environment-like-cluster-m-1-mac-linux

- src/executor/heredoc.c
> HS-92 FEAT: 히어독 달러치환

- include/minishell.h
- src/utils/env_utils/env_key_valid_checker.c
- src/utils/replace_dollar/replace_dollar.c
- src/utils/replace_dollar/replace_dollar_append_utils.c
- src/utils/replace_dollar/replace_dollar_len_utils.c
하이픈은 달러치환에서 인식하지 않음
`$USER---`이면 seongyle---으로 치환함
> HS-95 FIX: 하이픈는 치환범위가 아님

- src/init.c
- src/parser/process_list_utils.c
- src/utils/free_utils/free_utils.c
- src/utils/replace_dollar/replace_dollar.c
이제 executor 이외에서 leak이 나지 않을 것 같습니다.
> HS-99 FIX: argv envp leak 잡기, pipe 예외처리

- include/minishell.h
- src/executor/executor.c
- src/executor/heredoc.c
- src/executor/redirect.c
- src/init.c
히어독이 예상대로 작동합니다
heredoc 입력 시 .temp[숫자] 파일 생성
실행 시 .temp[숫자] 파일을 입력받음
이전 로직과 달리 token 을 직접 수정하지 않음. ( << a 를 < .temp0 으로 수정하지 않는다는 뜻 )
> HS-100-heredoc-debugging

- src/init.c
- src/parser/split/ft_split.c
input 이 Null 일 때 last status로 나가기입니다
아주 간단한 풀리퀘스트이지요.
> HS-104 REFACT: input 이 Null 일 때 last status로 나가기

- src/executor/redirect.c
redirect '>' error
dup2 를 stdout 에 연결
)
> HS-107-redirect-error

- include/minishell.h
- src/executor/heredoc.c
- src/executor/pipe.c
- src/executor/redirect.c
- src/executor/wait.c
함수명 앞에 <kdb>_</kbd>가 오는 것들 제거
불필요한 헤더 제거
> Hs 110 함수 이름 통일성 작업 언더바제거

- src/parser/set_process_list.c
> HS-117 REFACT: process list 함수 삭제

- src/executor/is_func.c
command not found 변경
: command not found[error_msg]
:command not found : [error_msg]
> HS-119-command-not-found-보기-좋게-변경

- Makefile
- include/minishell.h
- src/init.c
- src/utils/env_utils/env_key_valid_checker.c
- src/utils/replace_dollar/replace_dollar_is_utils.c
- src/utils/replace_dollar/replace_dollar_len_utils.c
- src/utils/replace_dollar/replace_dollar_utils.c
> HS-120 FIX: $? 뒤에 바로 문자열이 들어올 경우 처리

- .gitignore
- src/built_in/ft_export.c
- src/utils/ft_error.c
export 에러 메시지 수정
에러메시지 수정
이전
이후
x 는 글자색으로 인해서 생기는 오류
> Hs 123 minishell tester export error

- include/minishell.h
- src/executor/executor.c
- src/executor/is_func.c
… 많은지 검사하는 프로세스 추가
제곧내
is_heredoc_error() 함수 추가
execute_heredoc() 전에 에러처리 구문 추가
> HS-128-heredoc-16-개-초과시-segfault-로-종료되는-에러

- src/executor/executor.c
- src/executor/is_func.c
- src/executor/kill_all_childs.c
- src/executor/redirect.c
- src/executor/safe_func.c
- src/executor/wait.c
> HS-133-executor-norminette-맞추기
